export default {
  mainColor: '#105943',
  subColor: '#ffffff',
  blackTextColor: '#000000',
  whiteTextColor: '#ffffff',
  backGroundColor: '#ffffff',
  borderBottomColor: '#dcdcdc',
  activityIndicatorColor: '#bbbbbb',
  bioMetricColor: '#262626',
  warningColor: '#ff0000',
  grayColor: '#808080',
  lightGrayColor: '#bbbbbb',
  lightGray: '#dddddd',
  darkGrayColor: '#565656',
  AppLockOffColor: '#b0b0b0',
  redColor: '#ff6e6e',
  sanjiBackColor: '#dcdcdc',
  sanjiTextColor: '#888888',
};
