require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'gru_wallet_rn' do
  config = use_native_modules!

  pod 'Permission-Camera', :path => "../node_modules/react-native-permissions/ios/Camera.podspec"
  pod 'Firebase/Analytics'


  use_react_native!(:path => config["reactNativePath"])

  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'react-native-notifications', :path => '../node_modules/react-native-notifications'

  pod 'react-native-version-check', :path => '../node_modules/react-native-version-check'


  pod 'CodePush', :path => '../node_modules/react-native-code-push'

  target 'gru_wallet_rnTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!  code-push settings
  use_flipper!({ 'Flipper-Folly' => '2.3.0' })
  post_install do |installer|
    flipper_post_install(installer)
  end
end
